version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: cft-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: cft-backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: cft-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
